# Generated by Django 2.2.4 on 2019-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_email', models.CharField(max_length=20)),
                ('books_name', models.CharField(max_length=80)),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.TextField(max_length=1000)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
