# Generated by Django 2.2.4 on 2019-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_email', models.CharField(max_length=40)),
                ('books_name', models.CharField(max_length=80)),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.TextField(max_length=1000)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
